version: '3.8'
services:
  almacen2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: almacen2
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - mynet

    links:
      - microordenes
      - microusuarios
      - microproductos

  microordenes:
    build: ./microOrdenes
    ports:
      - "3003:3003"
    networks:
      - mynet
    links:
      - almacen2
      - microusuarios
      - microproductos

  microproductos:
    ports:
      - "3002:3002"
    build: ./microProductos
    networks:
      - mynet
    links:
      - almacen2
      - microusuarios
      - microordenes

  microusuarios:
    ports:
      - "3001:3001"
    build: ./microUsuarios
    networks:
      - mynet
    links:
      - almacen2
      - microordenes
      - microproductos

  microweb:
    build: ./microweb
    ports:
      - "80:80"
    networks:
      - mynet

volumes:
  db_data:


networks:
  mynet:
