# Usar una imagen base de PHP con Apache
# Revisar la version de la imagen para el despliegue 
FROM php:8.1.18-apache

# Copiar el código fuente del frontend
COPY . /var/www/html/

# Exponer el puerto en el que se ejecuta el servidor Apache
EXPOSE 80
